# Generated by Django 3.0.8 on 2020-08-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclegroup',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
