# Generated by Django 3.0.8 on 2020-08-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_musclegroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='main_muscle_groups',
            field=models.ManyToManyField(blank='True', related_name='exercies', to='exercise.MuscleGroup'),
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='exercises',
            field=models.ManyToManyField(blank='True', related_name='muscleGroup', to='exercise.Exercise'),
        ),
    ]
