# Generated by Django 3.0.8 on 2020-08-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_auto_20200817_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='time_to_complete',
            field=models.IntegerField(),
        ),
    ]
