# Generated by Django 3.0.8 on 2020-08-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_auto_20200817_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
