# Generated by Django 3.0.8 on 2020-08-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20200817_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('muscleGroup', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='main_muscle_groups',
        ),
        migrations.DeleteModel(
            name='MuscleGroup',
        ),
        migrations.AddField(
            model_name='muscle',
            name='exercises',
            field=models.ManyToManyField(blank='True', related_name='muscle', to='exercise.Exercise'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='main_muscles',
            field=models.ManyToManyField(blank='True', related_name='exercies', to='exercise.Muscle'),
        ),
    ]
