# Generated by Django 3.0.8 on 2020-08-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0009_auto_20200817_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='lower_or_upper',
            field=models.CharField(max_length=50),
        ),
    ]
