# Generated by Django 3.0.8 on 2020-08-20 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_auto_20200817_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='lower_or_upper',
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name='User_workouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('exercises', models.ManyToManyField(to='exercise.Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Starting_and_max',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_weight', models.IntegerField(blank='True')),
                ('max_weight', models.IntegerField(blank='True')),
                ('competed_before', models.BooleanField(default='False')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_weight', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Muscle_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=25)),
                ('muscles_in_group', models.ManyToManyField(to='exercise.Exercise')),
            ],
        ),
    ]
