# Generated by Django 3.0.8 on 2020-09-04 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_auto_20200819_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_workouts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myWorkouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
