# Generated by Django 3.0.8 on 2020-09-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0013_auto_20200905_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='muscleGroup',
            field=models.CharField(max_length=50),
        ),
    ]
