# Generated by Django 3.0.8 on 2020-09-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0020_auto_20200905_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_workouts',
            name='description',
            field=models.TextField(default=12, max_length=500),
            preserve_default=False,
        ),
    ]
