# Generated by Django 3.0.8 on 2020-09-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0021_user_workouts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_workouts',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_workouts',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
