# Generated by Django 3.0.8 on 2020-09-10 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0022_auto_20200910_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_workouts',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
