# Generated by Django 3.0.8 on 2020-09-30 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0023_user_workouts_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_workouts',
            name='users_who_liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
